grid_map_filters:
  - name: threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layers: [elevation]
      lower_threshold: 0.0
      set_to: .nan
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: elevation
      output_layer: inpainted
      radius: 0.05
  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: inpainted
      output_layer: averaged
      radius: 0.05
  - name: normal_vectors
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: inpainted
      output_layers_prefix: normal_vectors_
      radius: 0.04
      normal_vector_positive_axis: z
  - name: traversability_slope
    type: gridMapFilters/MathExpressionFilter
    params:
      expression: cwiseMax(1.0 - (acos(normal_vectors_z) / 0.78), 0.0)
      output_layer: traversability

#  - name: surfaceNormalsFilter
#    type: traversabilityFilters/SurfaceNormalsFilter
#    params:
#      estimation_radius: 0.05
#      surface_normal_positive_axis: "z"
#  - name: slopeFilter
#    type: traversabilityFilters/SlopeFilter
#    params:
#      map_type: traversability_slope
#      critical_value: 1.0
#  - name: stepFilter
#    type: traversabilityFilters/StepFilter
#    params:
#      map_type: traversability_step
#      critical_value: 0.12
#      first_window_radius: 0.04
#      second_window_radius: 0.04
#      critical_cell_number: 4
#  - name: roughnessFilter
#    type: traversabilityFilters/RoughnessFilter
#    params:
#      map_type: traversability_roughness
#      critical_value: 0.05
#      estimation_radius: 0.05
#  - name: weightedSumFilter
#    type: gridMapFilters/WeightedSumFilter
#    params:
#      layers: [traversability_slope, traversability_step, traversability_roughness]
#      weights: [1, 1, 1]
#      layer_out: traversability
#      normalize: 1
#  - name: deletionFilter
#    type: gridMapFilters/DeletionFilter
#    params:
#      layers: [surface_normal_x, surface_normal_y, surface_normal_z]
