grid_map_topic: /image_to_gridmap/image_grid_map

grid_map_visualizations:

  - name: elevation_cloud
    type: point_cloud
    params:
     layer: elevation

  - name: map_region
    type: map_region
    params:
     color: 16777215
     line_width: 0.003
